development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: school_system_development
  pool: 5
  username: root
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: school_system_test
  pool: 5
  username: root
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: school_system_production
  pool: 5
  username: root
  host: localhost